/**
 * AES-256-GCM cross-language parity test vector.
 *
 * PROVENANCE (D-05): Generated by a throwaway Java program (JVM 21) using
 * javax.crypto.Cipher("AES/GCM/NoPadding") — the same JVM crypto API as
 * Android EncryptionManager.kt (which runs on the same JVM stack). The Java
 * program is not committed; only these constants are. The Java generator mirrors
 * the Kotlin snippet from 120-RESEARCH.md §Pattern 2.
 *
 * KEY MATERIAL (NOT a real key — fixed deterministic value for testing only):
 *   ByteArray(32) { it.toByte() } in Kotlin = bytes 0x00..0x1F in Java:
 *   byte[] rawKey = new byte[32]; for (int i = 0; i < 32; i++) rawKey[i] = (byte) i;
 *
 * GENERATION STEPS (to regenerate):
 *   1. Create GenVector.java with:
 *        byte[] rawKey = new byte[32]; for (int i = 0; i < 32; i++) rawKey[i] = (byte) i;
 *        SecretKeySpec key = new SecretKeySpec(rawKey, "AES");
 *        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
 *        cipher.init(Cipher.ENCRYPT_MODE, key);
 *        byte[] iv = cipher.getIV(); // 12 bytes, JVM-random
 *        byte[] ct = cipher.doFinal("calicomp-parity-v1".getBytes("UTF-8")); // ct + 16-byte GCM tag
 *        // encode with java.util.Base64.getEncoder() (no line wrap = Android Base64.NO_WRAP)
 *   2. Run: javac GenVector.java && java GenVector
 *   3. Paste the printed KEY_B64, IV_B64, CT_B64 here.
 *
 * WIRE FORMAT invariants (source: EncryptionManager.kt lines 53–59):
 *   - Algorithm: AES/GCM/NoPadding
 *   - Key: 32 bytes (AES-256), base64-encoded (standard RFC 4648, no padding strip)
 *   - IV: 12 bytes, JVM-random (chosen by Cipher.init in ENCRYPT_MODE)
 *   - CT: ciphertext WITH 16-byte GCM auth tag APPENDED by Cipher.doFinal()
 *   - Base64: standard (NOT URL-safe); the IV "jXdyP+q3ehpupb4v" contains '+' which
 *     exercises the base64 vs base64url distinction (Pitfall 6 from 120-RESEARCH.md).
 */

/** Raw AES-256 key as standard base64 (key bytes: 0x00..0x1F, 32 bytes total). */
export const VECTOR_KEY_B64 = 'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=';

/** Known plaintext that was encrypted to produce VECTOR_CIPHERTEXT_JSON. */
export const VECTOR_PLAINTEXT = 'calicomp-parity-v1';

/**
 * AES-256-GCM ciphertext in EncryptionManager.kt wire format.
 * {"iv":"<12-byte IV, base64>","ct":"<ciphertext+16-byte GCM tag, base64>"}
 *
 * IV "jXdyP+q3ehpupb4v" contains '+' — must decode with 'base64' not 'base64url'.
 */
export const VECTOR_CIPHERTEXT_JSON =
  '{"iv":"jXdyP+q3ehpupb4v","ct":"RQqmIIQQXAUAceFf5gfEuju6OGkz9SO4qRdIhcE6aD7jtw=="}';
